### ISSUE TITLE
Ebook contents popover does not conform to standard visual theme

### ISSUE THREAD

**Issue by randy-jr-olive** [rschroll/beru#66]
The popover that displays the ebook's contents appears and hovers far away from the toolbar. This differs from the standard style of appearing right next to the toolbar and showing a little triangle to indicate the button that spawned the popover list.
Image on left is the "odd" popover, and on the right is the tradition popover.

![beru-pop-over-bug](https://cloud.githubusercontent.com/assets/8314978/4143851/f57ad758-33d2-11e4-8c4b-81235ca26697.png)

This may be a bug due to the custom bottom panel on the book page.

**Comment by rschroll** [comment]
This popover is gone, so I'm closing this bug.
