### ISSUE TITLE
beru crashes when ebook opened a second time

### ISSUE THREAD

**Issue by rhersel** [rschroll/beru#79]
On my bq Auquaris E4.5 Ubuntu Edition mobile phone, beru can open any epub but only for the first time. Whenever I open it a second time, beru crashes without any error message.

**Comment by rschroll** [comment]
That's weird.

There should be some log files in ~/.cache/upstart/.  If you could post 
them here or email them to me (rschroll at gmail), they may give us 
some clues.

**Comment by rhersel** [comment]
Yesterday I deleted the database to see if this makes any difference. Same behaviour: first time you open a book it is ok, second time it crashes. I will provide the log files as soon as possible.

**Comment by rhersel** [comment]
Here is the complete zipped cache folder: https://owncloud.rum3ber.ch/public.php?service=files&t=791dac3a66904f4bfba363894f205de2

**Comment by rhersel** [comment]
Here are all the beru related files from ~/.cache/upstart/. Let me know if you need other files: https://owncloud.rum3ber.ch/public.php?service=files&t=34656868aba4de7ef88c15d2919f7aca

**Comment by rhersel** [comment]
I re-installed Beru completely and so far I don't see this problem anymore. Seems to me that the issue was rather caused by settings: grey-on-dark background is not visible (black-on-black) and font size changes crashes Beru. I will investigate further.

**Comment by rschroll** [comment]
The database issue may be a big clue.  Which database did you delete, 
BeruBookSettings.db or the ones in Databases/?  If it was both, try 
deleting them one at a time and see which restores functionality.  
Perhaps there's a database corruption issue.

Those are indeed the files from .cache/upstart that I wanted.  
Unfortunately, they don't tell me anything useful.

I didn't understand your last comment -- have you found a way to cause 
a crash by changing the settings, or are you speculating that those 
used to cause the crash?

**Comment by rhersel** [comment]
Regarding my last comment: reinstalling Beru fixed the issues that I had before (for whatever reason). So let's close this thread. Regarding the 'dark background' issue I will open a new one.
